artists = [
    "🇦🇺 Australia – Go-Jo – Milkshake Man",
    "🇲🇪 Czarnogóra – Nina Žižić – Dobrodošli",
    "🇮🇪 Irlandia – Emmy – Laika Party",
    "🇱🇻 Łotwa – Tautumeitas – Bur man laimi",
    "🇦🇲 Armenia – Parg – Survivor",
    "🇦🇹 Austria – JJ – Wasted Love",
    "🇬🇷 Grecja – Klavdia – Asteromata",
    "🇱🇹 Litwa – Katarsis – Tavo akys",
    "🇲🇹 Malta – Miriana Conte – Serving",
    "🇬🇪 Gruzja – Mariam Shengelia – Freedom",
    "🇩🇰 Dania – Sissal – Hallucination",
    "🇨🇿 Czechy – Adonxs – Kiss Kiss Goodbye",
    "🇱🇺 Luksemburg – Laura Thorn – La poupée monte le son",
    "🇮🇱 Izrael – Yuval Raphael – New Day Will Rise",
    "🇷🇸 Serbia – Princ – Mila",
    "🇫🇮 Finlandia – Erika Vikman – Ich Komme",

    "🇮🇸 Islandia – Væb – Róa",
    "🇵🇱 Polska – Justyna Steczkowska – Gaja",
    "🇪🇪 Estonia – Tommy Cash – Espresso macchiato",
    "🇺🇦 Ukraina – Ziferblat – Bird of Pray",
    "🇸🇪 Szwecja – KAJ – Bara bada bastu",
    "🇵🇹 Portugalia – Nena – Deslocado",
    "🇳🇴 Norwegia – Kyle Alessandro – Lighter",
    "🇸🇲 San Marino – Megara – Tutta l'Italia",
    "🇦🇱 Albania – Besa – Zjerm",
    "🇳🇱 Niderlandy – Claude – C'est La Vie"
]