artists = [
    "🇳🇴 Norwegia – Kyle Alessandro – Lighter",
    "🇱🇺 Luksemburg – Laura Thorn – La poupée monte le son",
    "🇪🇪 Estonia – Tommy Cash – Espresso macchiato",
    "🇮🇱 Izrael – Yuval Raphael – New Day Will Rise",
    "🇱🇹 Litwa – Katarsis – Tavo akys",
    "🇪🇸 Hiszpania – Melody – Esa diva",
    "🇺🇦 Ukraina – Ziferblat – Bird of Pray",
    "🇬🇧 Wielka Brytania – Remember Monday – What the Hell Just Happened?",
    "🇦🇹 Austria – JJ – Wasted Love",
    "🇮🇸 Islandia – Væb – Róa",
    "🇱🇻 Łotwa – Tautumeitas – Bur man laimi",
    "🇳🇱 Niderlandy – Claude – C'est La Vie",
    "🇫🇮 Finlandia – Erika Vikman – Ich Komme",
    "🇮🇹 Włochy – Lucio Corsi – Volevo essere un duro",    
    "🇵🇱 Polska – Justyna Steczkowska – Gaja",
    "🇩🇪 Niemcy – Abor & Tynna – Baller",
    "🇬🇷 Grecja – Klavdia – Asteromata",
    "🇦🇲 Armenia – Parg – Survivor",
    "🇨🇭 Szwajcaria - Zoë Më - Voyage",
    "🇲🇹 Malta – Miriana Conte – Serving",    
    "🇵🇹 Portugalia – Nena – Deslocado",
    "🇩🇰 Dania – Sissal – Hallucination",
    "🇸🇪 Szwecja – KAJ – Bara bada bastu",
    "🇫🇷 Francja – Louane – Maman",
    "🇸🇲 San Marino – Gabry Ponte – Tutta l'Italia",
    "🇦🇱 Albania – Besa – Zjerm"
]
